// Copyright 2026 Keyfactor
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"html"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

const generatedMarker = "<!-- Generated by tools/storetypedocs. -->"

var (
	sourcePath = flag.String("source", "cmd/store_types.json", "path to store_types.json")
	pamPath    = flag.String("pam-source", "cmd/pam_types.json", "path to pam_types.json")
	outputDir  = flag.String("out", "docs/use-cases/Certificate Store Operations/Store Types", "output directory for generated docs")
)

type storeType struct {
	Name                     string              `json:"Name"`
	ShortName                string              `json:"ShortName"`
	Capability               string              `json:"Capability"`
	StorePathType            string              `json:"StorePathType"`
	StorePathValue           any                 `json:"StorePathValue"`
	StorePathDescription     string              `json:"StorePathDescription"`
	ClientMachineDescription string              `json:"ClientMachineDescription"`
	ServerRequired           bool                `json:"ServerRequired"`
	CustomAliasAllowed       string              `json:"CustomAliasAllowed"`
	PrivateKeyAllowed        string              `json:"PrivateKeyAllowed"`
	LocalStore               bool                `json:"LocalStore"`
	BlueprintAllowed         bool                `json:"BlueprintAllowed"`
	PowerShell               bool                `json:"PowerShell"`
	Properties               []storeTypeProperty `json:"Properties"`
	EntryParameters          []entryParameter    `json:"EntryParameters"`
	PasswordOptions          passwordOptions     `json:"PasswordOptions"`
	SupportedOperations      map[string]bool     `json:"SupportedOperations"`
}

type storeTypeProperty struct {
	Name          string `json:"Name"`
	DisplayName   string `json:"DisplayName"`
	Description   string `json:"Description"`
	Type          string `json:"Type"`
	DependsOn     any    `json:"DependsOn"`
	DefaultValue  any    `json:"DefaultValue"`
	Required      bool   `json:"Required"`
	IsPAMEligible bool   `json:"IsPAMEligible"`
	IsPamEligable bool   `json:"IsPamEligable"`
	Options       any    `json:"Options"`
}

type entryParameter struct {
	Name         string `json:"Name"`
	DisplayName  string `json:"DisplayName"`
	Description  string `json:"Description"`
	Type         string `json:"Type"`
	DependsOn    any    `json:"DependsOn"`
	DefaultValue any    `json:"DefaultValue"`
	RequiredWhen any    `json:"RequiredWhen"`
	Options      any    `json:"Options"`
}

type passwordOptions struct {
	Style          string         `json:"Style"`
	EntrySupported bool           `json:"EntrySupported"`
	StoreRequired  bool           `json:"StoreRequired"`
	StorePassword  *storePassword `json:"StorePassword"`
}

type storePassword struct {
	Description   string `json:"Description"`
	IsPAMEligible bool   `json:"IsPAMEligible"`
}

type pamType struct {
	Name       string         `json:"Name"`
	Parameters []pamParameter `json:"Parameters"`
}

type pamParameter struct {
	Name          string `json:"Name"`
	DisplayName   string `json:"DisplayName"`
	Description   string `json:"Description"`
	DataType      int    `json:"DataType"`
	InstanceLevel bool   `json:"InstanceLevel"`
}

func main() {
	flag.Parse()

	storeTypes, err := readStoreTypes(*sourcePath)
	if err != nil {
		fatal(err)
	}
	pamTypes, err := readPAMTypes(*pamPath)
	if err != nil {
		fatal(err)
	}

	sort.Slice(storeTypes, func(i, j int) bool {
		return strings.ToLower(storeTypes[i].ShortName) < strings.ToLower(storeTypes[j].ShortName)
	})
	sort.Slice(pamTypes, func(i, j int) bool {
		return strings.ToLower(pamTypes[i].Name) < strings.ToLower(pamTypes[j].Name)
	})

	slugs := uniqueSlugs(storeTypes)

	if err := os.MkdirAll(*outputDir, 0o755); err != nil {
		fatal(err)
	}
	if err := removeStaleGeneratedDocs(*outputDir); err != nil {
		fatal(err)
	}

	for _, st := range storeTypes {
		fileName := slugs[st.ShortName] + ".md"
		path := filepath.Join(*outputDir, fileName)
		if err := os.WriteFile(path, []byte(renderStoreTypeDoc(st, pamTypes)), 0o644); err != nil {
			fatal(fmt.Errorf("write %s: %w", path, err))
		}
	}

	indexPath := filepath.Join(*outputDir, "README.md")
	if err := os.WriteFile(indexPath, []byte(renderIndex(storeTypes, slugs, pamTypes)), 0o644); err != nil {
		fatal(fmt.Errorf("write %s: %w", indexPath, err))
	}

	fmt.Printf("Generated %d store type docs in %s\n", len(storeTypes), *outputDir)
}

func readStoreTypes(path string) ([]storeType, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}

	var storeTypes []storeType
	if err := json.Unmarshal(data, &storeTypes); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	if len(storeTypes) == 0 {
		return nil, fmt.Errorf("%s did not contain any store types", path)
	}
	for i := range storeTypes {
		if storeTypes[i].ShortName == "" {
			return nil, fmt.Errorf("store type at index %d is missing ShortName", i)
		}
	}
	return storeTypes, nil
}

func readPAMTypes(path string) ([]pamType, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}

	var pamTypes []pamType
	if err := json.Unmarshal(data, &pamTypes); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	if len(pamTypes) == 0 {
		return nil, fmt.Errorf("%s did not contain any PAM types", path)
	}
	for i := range pamTypes {
		if pamTypes[i].Name == "" {
			return nil, fmt.Errorf("PAM type at index %d is missing Name", i)
		}
	}
	return pamTypes, nil
}

func removeStaleGeneratedDocs(dir string) error {
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}

	for _, entry := range entries {
		if entry.IsDir() || filepath.Ext(entry.Name()) != ".md" {
			continue
		}
		path := filepath.Join(dir, entry.Name())
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if bytes.Contains(data, []byte(generatedMarker)) {
			if err := os.Remove(path); err != nil {
				return err
			}
		}
	}
	return nil
}

func uniqueSlugs(storeTypes []storeType) map[string]string {
	counts := map[string]int{}
	slugs := map[string]string{}
	for _, st := range storeTypes {
		base := slugify(st.ShortName)
		if base == "" {
			base = slugify(st.Name)
		}
		if base == "" {
			base = "store-type"
		}
		counts[base]++
		slug := base
		if counts[base] > 1 {
			slug = fmt.Sprintf("%s-%d", base, counts[base])
		}
		slugs[st.ShortName] = slug
	}
	return slugs
}

func slugify(value string) string {
	value = strings.ToLower(value)
	re := regexp.MustCompile(`[^a-z0-9]+`)
	value = re.ReplaceAllString(value, "-")
	return strings.Trim(value, "-")
}

func renderIndex(storeTypes []storeType, slugs map[string]string, pamTypes []pamType) string {
	var b strings.Builder
	b.WriteString(generatedMarker + "\n")
	b.WriteString("# Store Type Bulk Create And Update Guides\n\n")
	b.WriteString("These docs are generated from `cmd/store_types.json` and `cmd/pam_types.json` and describe the CSV columns used by `kfutil stores import csv` for each embedded certificate store type.\n\n")
	b.WriteString("Regenerate after store type metadata changes:\n\n")
	b.WriteString("```bash\n")
	b.WriteString("make store-type-docs\n")
	b.WriteString("```\n\n")
	b.WriteString("Use `kfutil stores import generate-template` against a live Command environment when you need a template that reflects deployed customizations.\n\n")
	writePAMTypeIndex(&b, pamTypes)
	b.WriteString("## Store Types\n\n")
	b.WriteString("| Store Type | Name | Store Password | Secret/PAM Columns |\n")
	b.WriteString("| --- | --- | --- | --- |\n")
	for _, st := range storeTypes {
		secretCount := 0
		for _, prop := range st.Properties {
			if isSecretProperty(prop) {
				secretCount++
			}
		}
		b.WriteString(fmt.Sprintf("| [`%s`](%s.md) | %s | %s | %s |\n",
			mdTable(st.ShortName),
			slugs[st.ShortName],
			mdTable(st.Name),
			mdTable(storePasswordSummary(st.PasswordOptions)),
			mdTable(secretColumnSummary(secretCount)),
		))
	}
	return b.String()
}

func renderStoreTypeDoc(st storeType, pamTypes []pamType) string {
	var b strings.Builder
	title := st.ShortName
	if st.Name != "" {
		title += " - " + st.Name
	}

	b.WriteString(generatedMarker + "\n")
	b.WriteString("# " + title + "\n\n")
	b.WriteString("[Store Type Index](README.md) | [Certificate Store Operations](../README.md)\n\n")
	b.WriteString("Generated from `cmd/store_types.json`. Regenerate with:\n\n")
	b.WriteString("```bash\n")
	b.WriteString("make store-type-docs\n")
	b.WriteString("```\n\n")

	writeOverview(&b, st)
	writeBulkCreate(&b, st)
	writeBulkUpdate(&b, st)
	writeProperties(&b, st)
	writeEntryParameters(&b, st)
	writeSecretFormatting(&b, st, pamTypes)
	writeReferences(&b)

	return b.String()
}

func writeOverview(b *strings.Builder, st storeType) {
	b.WriteString("## Overview\n\n")
	b.WriteString("| Field | Value |\n")
	b.WriteString("| --- | --- |\n")
	b.WriteString(fmt.Sprintf("| Store type | `%s` |\n", mdTable(st.ShortName)))
	b.WriteString(fmt.Sprintf("| Name | %s |\n", mdTable(st.Name)))
	b.WriteString(fmt.Sprintf("| Capability | %s |\n", mdTable(blank(st.Capability))))
	b.WriteString(fmt.Sprintf("| Server required | %s |\n", yesNo(st.ServerRequired)))
	b.WriteString(fmt.Sprintf("| Store path type | %s |\n", mdTable(value(st.StorePathType))))
	b.WriteString(fmt.Sprintf("| Store path value | %s |\n", mdTable(value(st.StorePathValue))))
	b.WriteString(fmt.Sprintf("| Custom alias | %s |\n", mdTable(blank(st.CustomAliasAllowed))))
	b.WriteString(fmt.Sprintf("| Private key | %s |\n", mdTable(blank(st.PrivateKeyAllowed))))
	b.WriteString(fmt.Sprintf("| Store password | %s |\n", mdTable(storePasswordSummary(st.PasswordOptions))))
	b.WriteString(fmt.Sprintf("| Supported operations | %s |\n\n", mdTable(supportedOperations(st.SupportedOperations))))

	if st.ClientMachineDescription != "" {
		b.WriteString("**ClientMachine:** " + mdText(st.ClientMachineDescription) + "\n\n")
	}
	if st.StorePathDescription != "" {
		b.WriteString("**StorePath:** " + mdText(st.StorePathDescription) + "\n\n")
	}
}

func writeBulkCreate(b *strings.Builder, st storeType) {
	b.WriteString("## Bulk Create\n\n")
	b.WriteString("Use one CSV per store type. The generated create headers for this store type are:\n\n")
	b.WriteString("```csv\n")
	b.WriteString(strings.Join(createHeaders(st), ",") + "\n")
	b.WriteString("```\n\n")
	b.WriteString("Create stores from the CSV:\n\n")
	b.WriteString("```bash\n")
	b.WriteString(fmt.Sprintf("kfutil stores import csv \\\n  --file %s_bulk_create.csv \\\n  --store-type-name %s \\\n  --no-prompt\n", shellName(st.ShortName), shellQuote(st.ShortName)))
	b.WriteString("```\n\n")
	b.WriteString("To generate a live template from Command instead of using the static header list above:\n\n")
	b.WriteString("```bash\n")
	b.WriteString(fmt.Sprintf("kfutil stores import generate-template \\\n  --store-type-name %s \\\n  --outpath %s_bulk_create_template.csv \\\n  --no-prompt\n", shellQuote(st.ShortName), shellName(st.ShortName)))
	b.WriteString("```\n\n")
}

func writeBulkUpdate(b *strings.Builder, st storeType) {
	b.WriteString("## Bulk Update\n\n")
	b.WriteString("Export existing stores, edit the desired columns, then sync the rows back by `Id`:\n\n")
	b.WriteString("```bash\n")
	b.WriteString(fmt.Sprintf("kfutil stores export \\\n  --store-type-name %s \\\n  --outpath %s_export.csv \\\n  --no-prompt\n\n", shellQuote(st.ShortName), shellName(st.ShortName)))
	b.WriteString(fmt.Sprintf("kfutil stores import csv \\\n  --file %s_export.csv \\\n  --store-type-name %s \\\n  --sync \\\n  --no-prompt\n", shellName(st.ShortName), shellQuote(st.ShortName)))
	b.WriteString("```\n\n")
	b.WriteString("Minimum sync rows must include `Id`. Keep `ClientMachine`, `StorePath`, and any unchanged property columns in the export unless you intentionally want to update them.\n\n")
	b.WriteString("Common update headers for this store type are:\n\n")
	b.WriteString("```csv\n")
	b.WriteString(strings.Join(updateHeaders(st), ",") + "\n")
	b.WriteString("```\n\n")
}

func writeProperties(b *strings.Builder, st storeType) {
	b.WriteString("## Store Properties\n\n")
	if len(st.Properties) == 0 {
		b.WriteString("This store type does not define additional `Properties.*` CSV columns.\n\n")
		return
	}

	b.WriteString("| CSV column | Display name | Type | Required | Default | Depends on | Secret/PAM | Description |\n")
	b.WriteString("| --- | --- | --- | --- | --- | --- | --- | --- |\n")
	for _, prop := range st.Properties {
		b.WriteString(fmt.Sprintf("| `Properties.%s` | %s | %s | %s | %s | %s | %s | %s |\n",
			mdTable(prop.Name),
			mdTable(blank(prop.DisplayName)),
			mdTable(blank(prop.Type)),
			yesNo(prop.Required),
			mdTable(value(prop.DefaultValue)),
			mdTable(value(prop.DependsOn)),
			mdTable(secretPropertySummary(prop)),
			mdTable(blank(prop.Description)),
		))
	}
	b.WriteString("\n")
}

func writeEntryParameters(b *strings.Builder, st storeType) {
	if len(st.EntryParameters) == 0 {
		return
	}

	b.WriteString("## Certificate Entry Parameters\n\n")
	b.WriteString("These parameters apply to certificate add/enrollment operations for this store type. They are not store create/sync CSV columns unless another workflow explicitly asks for them.\n\n")
	b.WriteString("| Name | Display name | Type | Required when | Default | Depends on | Description |\n")
	b.WriteString("| --- | --- | --- | --- | --- | --- | --- |\n")
	for _, param := range st.EntryParameters {
		b.WriteString(fmt.Sprintf("| `%s` | %s | %s | %s | %s | %s | %s |\n",
			mdTable(param.Name),
			mdTable(blank(param.DisplayName)),
			mdTable(blank(param.Type)),
			mdTable(value(param.RequiredWhen)),
			mdTable(value(param.DefaultValue)),
			mdTable(value(param.DependsOn)),
			mdTable(blank(param.Description)),
		))
	}
	b.WriteString("\n")
}

func writeSecretFormatting(b *strings.Builder, st storeType, pamTypes []pamType) {
	secretProps := secretProperties(st)
	storePasswordEligible := st.PasswordOptions.StorePassword != nil && st.PasswordOptions.StorePassword.IsPAMEligible
	if len(secretProps) == 0 && !storePasswordEligible {
		return
	}

	b.WriteString("## Secret And PAM Formatting\n\n")
	if len(secretProps) > 0 {
		b.WriteString("Direct secret values go in the base property column. If the secret value is JSON, keep the entire JSON document in one quoted CSV cell.\n\n")
		b.WriteString("```csv\n")
		for _, prop := range secretProps {
			b.WriteString(fmt.Sprintf("Properties.%s\n", prop.Name))
		}
		b.WriteString("```\n\n")
		b.WriteString("PAM-backed property secrets use a provider column and provider-type-specific parameter columns. `Provider` identifies the configured PAM provider. `Parameters.*` must match the instance-level parameters for that provider type.\n\n")
		b.WriteString("```csv\n")
		for _, prop := range secretProps {
			b.WriteString(fmt.Sprintf("Properties.%s.Provider,Properties.%s.Parameters.<ParameterName>\n", prop.Name, prop.Name))
		}
		b.WriteString("```\n\n")
		b.WriteString("Use the PAM parameter names in the table below, or check the provider type in Command if your environment uses custom PAM types.\n\n")
	}
	if st.PasswordOptions.StorePassword != nil {
		b.WriteString("The store password uses the `Password` column. ")
		if st.PasswordOptions.StorePassword.IsPAMEligible {
			b.WriteString("For a PAM-backed store password, use `Password.Provider` and `Password.Parameters.<ParameterName>` columns. The `Parameters.*` columns must match the instance-level parameters for the configured PAM provider type.\n\n")
		} else {
			b.WriteString("This store type metadata does not mark the store password as PAM eligible.\n\n")
		}
	}
	writePAMParameterTable(b, pamTypes)
}

func writePAMTypeIndex(b *strings.Builder, pamTypes []pamType) {
	b.WriteString("## PAM Provider Parameter Columns\n\n")
	b.WriteString("PAM-backed secret columns vary by PAM provider type. Certificate store CSV rows can only set the instance-level parameter names exposed to certificate stores, with the secret column prefix. For example, use `Properties.ServerPassword.Parameters.SecretId` or `Password.Parameters.SecretId`.\n\n")
	writePAMParameterTable(b, pamTypes)
}

func writePAMParameterTable(b *strings.Builder, pamTypes []pamType) {
	b.WriteString("| PAM type | Store CSV parameter names |\n")
	b.WriteString("| --- | --- |\n")
	for _, pamType := range pamTypes {
		b.WriteString(fmt.Sprintf("| `%s` | %s |\n",
			mdTable(pamType.Name),
			mdTable(strings.Join(instanceParameterNames(pamType.Parameters), ", ")),
		))
	}
	b.WriteString("\n")
}

func instanceParameterNames(parameters []pamParameter) []string {
	var names []string
	for _, parameter := range parameters {
		if parameter.InstanceLevel {
			names = append(names, parameter.Name)
		}
	}
	if len(names) == 0 {
		return []string{"-"}
	}
	return names
}

func writeReferences(b *strings.Builder) {
	b.WriteString("## References\n\n")
	b.WriteString("- [Bulk Certificate Store Creation](../bulk-certificate-store-creation.md)\n")
	b.WriteString("- [Bulk Certificate Store Updates](../bulk-certificate-store-updates.md)\n")
	b.WriteString("- [Migrate Static Store Credentials To A PAM Provider](../migrate-static-store-credentials-to-pam.md)\n")
	b.WriteString("- [kfutil stores import csv](../../../kfutil_stores_import_csv.md)\n")
	b.WriteString("- [kfutil stores import generate-template](../../../kfutil_stores_import_generate-template.md)\n")
}

func createHeaders(st storeType) []string {
	headers := []string{
		"ContainerId",
		"ClientMachine",
		"StorePath",
		"CreateIfMissing",
	}
	for _, prop := range st.Properties {
		headers = append(headers, "Properties."+prop.Name)
	}
	headers = append(headers,
		"AgentId",
		"InventorySchedule.Immediate",
		"InventorySchedule.Interval.Minutes",
		"InventorySchedule.Daily.Time",
		"InventorySchedule.Weekly.Days",
		"InventorySchedule.Weekly.Time",
	)
	if st.PasswordOptions.StoreRequired {
		headers = append(headers, "Password")
	}
	return headers
}

func updateHeaders(st storeType) []string {
	headers := append([]string{"Id"}, createHeaders(st)...)
	return headers
}

func secretProperties(st storeType) []storeTypeProperty {
	var props []storeTypeProperty
	for _, prop := range st.Properties {
		if isSecretProperty(prop) {
			props = append(props, prop)
		}
	}
	return props
}

func isSecretProperty(prop storeTypeProperty) bool {
	return strings.EqualFold(prop.Type, "Secret") || prop.IsPAMEligible || prop.IsPamEligable
}

func secretPropertySummary(prop storeTypeProperty) string {
	if !isSecretProperty(prop) {
		return "No"
	}
	if prop.IsPAMEligible || prop.IsPamEligable {
		return "Secret; PAM eligible"
	}
	return "Secret"
}

func storePasswordSummary(options passwordOptions) string {
	if options.StoreRequired {
		if options.StorePassword != nil && options.StorePassword.IsPAMEligible {
			return "Required; PAM eligible"
		}
		return "Required"
	}
	if options.StorePassword != nil && options.StorePassword.IsPAMEligible {
		return "Optional; PAM eligible"
	}
	return "Not required"
}

func secretColumnSummary(secretCount int) string {
	switch secretCount {
	case 0:
		return "None"
	case 1:
		return "1 secret property"
	default:
		return fmt.Sprintf("%d secret properties", secretCount)
	}
}

func supportedOperations(ops map[string]bool) string {
	if len(ops) == 0 {
		return "-"
	}
	var enabled []string
	for op, ok := range ops {
		if ok {
			enabled = append(enabled, op)
		}
	}
	sort.Strings(enabled)
	if len(enabled) == 0 {
		return "None"
	}
	return strings.Join(enabled, ", ")
}

func value(v any) string {
	if v == nil {
		return "-"
	}
	switch typed := v.(type) {
	case string:
		return blank(typed)
	case bool:
		return yesNo(typed)
	case float64:
		return fmt.Sprintf("%v", typed)
	default:
		data, err := json.Marshal(typed)
		if err != nil {
			return fmt.Sprintf("%v", typed)
		}
		return string(data)
	}
}

func blank(s string) string {
	if strings.TrimSpace(s) == "" {
		return "-"
	}
	return s
}

func yesNo(v bool) string {
	if v {
		return "Yes"
	}
	return "No"
}

func mdTable(s string) string {
	s = mdText(s)
	s = strings.ReplaceAll(s, "|", `\|`)
	return s
}

func mdText(s string) string {
	s = strings.TrimSpace(s)
	if s == "" {
		return "-"
	}
	s = html.EscapeString(s)
	s = strings.ReplaceAll(s, "\r\n", "\n")
	s = strings.ReplaceAll(s, "\r", "\n")
	s = strings.ReplaceAll(s, "\n", "<br>")
	return s
}

func shellName(value string) string {
	return slugify(value)
}

func shellQuote(value string) string {
	if regexp.MustCompile(`^[A-Za-z0-9._-]+$`).MatchString(value) {
		return value
	}
	return "'" + strings.ReplaceAll(value, "'", `'\''`) + "'"
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
