// Copyright 2026 Keyfactor
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package pamdocs

import (
	"bytes"
	"encoding/json"
	"fmt"
	"html"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

const generatedMarker = "<!-- Generated by tools/pamdocs. -->"

const (
	DefaultSourcePath = "cmd/pam_types.json"
	DefaultOutputDir  = "docs/use-cases/PAM Operations"
)

type pamType struct {
	Name       string         `json:"Name"`
	Parameters []pamParameter `json:"Parameters"`
}

type pamParameter struct {
	Name          string `json:"Name"`
	DisplayName   string `json:"DisplayName"`
	Description   string `json:"Description"`
	DataType      int    `json:"DataType"`
	InstanceLevel bool   `json:"InstanceLevel"`
}

type providerTemplate struct {
	Area                    int                          `json:"Area"`
	Name                    string                       `json:"Name"`
	Remote                  bool                         `json:"Remote"`
	ProviderType            providerTemplateType         `json:"ProviderType"`
	ProviderTypeParamValues []providerTemplateParamValue `json:"ProviderTypeParamValues"`
	SecuredAreaId           *int                         `json:"SecuredAreaId"`
}

type providerTemplateType struct {
	Id                 string                      `json:"Id"`
	Name               string                      `json:"Name"`
	ProviderTypeParams []providerTemplateParameter `json:"ProviderTypeParams"`
}

type providerTemplateParamValue struct {
	Value             string                    `json:"Value"`
	ProviderTypeParam providerTemplateParameter `json:"ProviderTypeParam"`
}

type providerTemplateParameter struct {
	Id            string `json:"Id"`
	Name          string `json:"Name"`
	DisplayName   string `json:"DisplayName,omitempty"`
	DataType      int    `json:"DataType"`
	InstanceLevel bool   `json:"InstanceLevel"`
}

func Generate(sourcePath, outputDir string) error {
	if sourcePath == "" {
		sourcePath = DefaultSourcePath
	}
	if outputDir == "" {
		outputDir = DefaultOutputDir
	}

	pamTypes, err := readPAMTypes(sourcePath)
	if err != nil {
		return err
	}
	sort.Slice(pamTypes, func(i, j int) bool {
		return strings.ToLower(pamTypes[i].Name) < strings.ToLower(pamTypes[j].Name)
	})

	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return err
	}

	files := map[string]string{
		"README.md":               renderIndex(pamTypes),
		"create-pam-types.md":     renderCreatePAMTypes(pamTypes),
		"create-pam-providers.md": renderCreatePAMProviders(pamTypes),
	}

	for name, content := range files {
		path := filepath.Join(outputDir, name)
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			return fmt.Errorf("write %s: %w", path, err)
		}
	}

	fmt.Printf("Generated PAM operation docs for %d PAM types in %s\n", len(pamTypes), outputDir)
	return nil
}

func readPAMTypes(path string) ([]pamType, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}

	var pamTypes []pamType
	if err := json.Unmarshal(data, &pamTypes); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	if len(pamTypes) == 0 {
		return nil, fmt.Errorf("%s did not contain any PAM types", path)
	}
	for i := range pamTypes {
		if pamTypes[i].Name == "" {
			return nil, fmt.Errorf("PAM type at index %d is missing Name", i)
		}
	}
	return pamTypes, nil
}

func renderIndex(pamTypes []pamType) string {
	var b strings.Builder
	b.WriteString(generatedMarker + "\n")
	b.WriteString("# PAM Operations\n\n")
	b.WriteString("Use cases for creating PAM provider types and PAM providers with `kfutil`.\n\n")
	b.WriteString("These docs are generated from `cmd/pam_types.json`. Regenerate after PAM type metadata changes:\n\n")
	b.WriteString("```bash\n")
	b.WriteString("kfutil makedocs\n")
	b.WriteString("```\n\n")
	b.WriteString("- [Create PAM Types](create-pam-types.md)\n")
	b.WriteString("- [Create PAM Providers](create-pam-providers.md)\n\n")
	writePAMTypeTable(&b, pamTypes)
	return b.String()
}

func renderCreatePAMTypes(pamTypes []pamType) string {
	var b strings.Builder
	b.WriteString(generatedMarker + "\n")
	b.WriteString("# Create PAM Types\n\n")
	b.WriteString("[PAM Operations](README.md) | [Use Cases](../README.md)\n\n")
	b.WriteString("This use case installs the PAM provider type definitions embedded in `cmd/pam_types.json`.\n\n")
	b.WriteString("## Create All Embedded PAM Types\n\n")
	b.WriteString("```bash\n")
	b.WriteString("kfutil pam-types create --all --no-prompt\n")
	b.WriteString("```\n\n")
	b.WriteString("## Create One PAM Type\n\n")
	b.WriteString("Use `--name` when you only want one provider type:\n\n")
	b.WriteString("```bash\n")
	b.WriteString("kfutil pam-types create --name Hashicorp-Vault --no-prompt\n")
	b.WriteString("```\n\n")
	b.WriteString("## Commands For Each Embedded PAM Type\n\n")
	for _, pamType := range pamTypes {
		b.WriteString("### " + pamType.Name + "\n\n")
		b.WriteString("```bash\n")
		b.WriteString(fmt.Sprintf("kfutil pam-types create --name %s --no-prompt\n", shellQuote(pamType.Name)))
		b.WriteString("```\n\n")
	}
	b.WriteString("## Verify\n\n")
	b.WriteString("```bash\n")
	b.WriteString("kfutil pam-types list --no-prompt\n")
	b.WriteString("```\n\n")
	writeReferences(&b)
	return b.String()
}

func renderCreatePAMProviders(pamTypes []pamType) string {
	var b strings.Builder
	b.WriteString(generatedMarker + "\n")
	b.WriteString("# Create PAM Providers\n\n")
	b.WriteString("[PAM Operations](README.md) | [Use Cases](../README.md)\n\n")
	b.WriteString("This use case creates PAM providers from JSON files. `kfutil pam create` currently accepts provider configuration with `--from-file`.\n\n")
	b.WriteString("Create the PAM provider type first, then create the provider that uses it:\n\n")
	b.WriteString("```bash\n")
	b.WriteString("kfutil pam-types create --name Hashicorp-Vault --no-prompt\n")
	b.WriteString("kfutil pam create --from-file hashicorp-vault-provider.json --no-prompt\n")
	b.WriteString("```\n\n")
	b.WriteString("Provider JSON contains provider-level connection settings only. Certificate-store instance parameters are not set on the provider; they are supplied later on certificate store CSV columns such as `Properties.ServerPassword.Parameters.SecretId`.\n\n")
	b.WriteString("Provider type IDs and provider parameter IDs are assigned by Command when PAM types are created. Get the live provider type first and replace the `Id` placeholders in the generated template before running `kfutil pam create`:\n\n")
	b.WriteString("```bash\n")
	b.WriteString("kfutil pam-types get --name Hashicorp-Vault --no-prompt\n")
	b.WriteString("```\n\n")
	writePAMTypeTable(&b, pamTypes)
	b.WriteString("## Provider Examples\n\n")
	for _, pamType := range pamTypes {
		writeProviderExample(&b, pamType)
	}
	writeReferences(&b)
	return b.String()
}

func writePAMTypeTable(b *strings.Builder, pamTypes []pamType) {
	b.WriteString("## Embedded PAM Types\n\n")
	b.WriteString("| PAM type | Provider configuration parameters | Certificate store instance parameters |\n")
	b.WriteString("| --- | --- | --- |\n")
	for _, pamType := range pamTypes {
		b.WriteString(fmt.Sprintf("| `%s` | %s | %s |\n",
			mdTable(pamType.Name),
			mdTable(strings.Join(parameterNames(pamType.Parameters, false), ", ")),
			mdTable(strings.Join(parameterNames(pamType.Parameters, true), ", ")),
		))
	}
	b.WriteString("\n")
}

func writeProviderExample(b *strings.Builder, pamType pamType) {
	fileName := slugify(pamType.Name) + "-provider.json"
	b.WriteString("### " + pamType.Name + "\n\n")
	b.WriteString("Write a provider config file:\n\n")
	b.WriteString("```json\n")
	b.WriteString(providerJSON(pamType))
	b.WriteString("\n```\n\n")
	b.WriteString("Create the provider:\n\n")
	b.WriteString("```bash\n")
	b.WriteString(fmt.Sprintf("kfutil pam create --from-file %s --no-prompt\n", fileName))
	b.WriteString("```\n\n")
}

func providerJSON(pamType pamType) string {
	providerParams := filterParameters(pamType.Parameters, false)
	templateParams := make([]providerTemplateParameter, 0, len(providerParams))
	templateValues := make([]providerTemplateParamValue, 0, len(providerParams))
	for _, param := range providerParams {
		templateParam := providerTemplateParameter{
			Id:            "<" + param.Name + "-parameter-id>",
			Name:          param.Name,
			DisplayName:   param.DisplayName,
			DataType:      param.DataType,
			InstanceLevel: param.InstanceLevel,
		}
		templateParams = append(templateParams, templateParam)
		templateValues = append(templateValues, providerTemplateParamValue{
			Value:             placeholderValue(param),
			ProviderTypeParam: templateParam,
		})
	}

	template := providerTemplate{
		Area:   1,
		Name:   "example-" + slugify(pamType.Name),
		Remote: false,
		ProviderType: providerTemplateType{
			Id:                 "<provider-type-id>",
			Name:               pamType.Name,
			ProviderTypeParams: templateParams,
		},
		ProviderTypeParamValues: templateValues,
		SecuredAreaId:           nil,
	}

	var out bytes.Buffer
	encoder := json.NewEncoder(&out)
	encoder.SetEscapeHTML(false)
	encoder.SetIndent("", "  ")
	err := encoder.Encode(template)
	if err != nil {
		panic(err)
	}
	return strings.TrimSpace(out.String())
}

func parameterNames(parameters []pamParameter, instanceLevel bool) []string {
	params := filterParameters(parameters, instanceLevel)
	if len(params) == 0 {
		return []string{"-"}
	}
	names := make([]string, 0, len(params))
	for _, param := range params {
		names = append(names, param.Name)
	}
	return names
}

func filterParameters(parameters []pamParameter, instanceLevel bool) []pamParameter {
	var filtered []pamParameter
	for _, param := range parameters {
		if param.InstanceLevel == instanceLevel {
			filtered = append(filtered, param)
		}
	}
	return filtered
}

func placeholderValue(param pamParameter) string {
	name := strings.ToLower(param.Name)
	if name == "clientid" || name == "clientsecret" {
		return "N/A"
	}
	if name == "granttype" {
		return "password"
	}
	if strings.Contains(name, "uri") || strings.Contains(name, "url") || strings.Contains(name, "host") {
		return "https://example.invalid"
	}
	if param.DataType == 2 || strings.Contains(name, "secret") || strings.Contains(name, "token") || strings.Contains(name, "password") || strings.Contains(name, "key") {
		return "<secret-value>"
	}
	return "<" + param.Name + ">"
}

func writeReferences(b *strings.Builder) {
	b.WriteString("## References\n\n")
	b.WriteString("- [kfutil pam create](../../kfutil_pam_create.md)\n")
	b.WriteString("- [kfutil pam list](../../kfutil_pam_list.md)\n")
	b.WriteString("- [kfutil pam-types create](../../kfutil_pam-types_create.md)\n")
	b.WriteString("- [kfutil pam-types list](../../kfutil_pam-types_list.md)\n")
}

func slugify(value string) string {
	value = strings.ToLower(value)
	re := regexp.MustCompile(`[^a-z0-9]+`)
	value = re.ReplaceAllString(value, "-")
	return strings.Trim(value, "-")
}

func shellQuote(value string) string {
	if regexp.MustCompile(`^[A-Za-z0-9._-]+$`).MatchString(value) {
		return value
	}
	return "'" + strings.ReplaceAll(value, "'", `'\''`) + "'"
}

func mdTable(s string) string {
	s = strings.TrimSpace(s)
	if s == "" {
		return "-"
	}
	s = html.EscapeString(s)
	s = strings.ReplaceAll(s, "|", `\|`)
	s = strings.ReplaceAll(s, "\r\n", "\n")
	s = strings.ReplaceAll(s, "\r", "\n")
	s = strings.ReplaceAll(s, "\n", "<br>")
	return s
}
