name: Go Test

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Install dependencies
        run: go mod download && go mod tidy

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az --version


  test-store-types:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get secret from Azure Key Vault
        run: |
          set -e -o pipefail # fail on any error and show what failed
          access_token=$(curl -s -H "Metadata: true" "http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https://vault.azure.net" | jq -r .access_token)
          mkdir -p ~/.keyfactor
          secret_value=$(az keyvault secret show --vault-name kfutil --name command_config --query "value" --output tsv --auth-type oauth2 --token $access_token)
          echo "$secret_value" > ~/.keyfactor/command_config.json
          cat ~/.keyfactor/command_config.json

      - name: Run tests
        run: go test ./cmd/storeTypes_test.go
