name: Go Test

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Install dependencies
        run: go mod download && go mod tidy

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az --version


  test-store-types:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to Azure
        uses: azure/login@v1

        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get secret from Azure Key Vault
        run: |
          set -e -o pipefail # fail on any error and show what failed
          mkdir -p ~/.keyfactor
          az keyvault secret show \
            --vault-name integrations \
            --name command_config \
            --query "value" \
            --output tsv > ~/.keyfactor/command_config.json
          cat ~/.keyfactor/command_config.json

      - name: Run tests
        run: go test ./cmd/storeTypes_test.go
