name: Go Test

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Install dependencies
        run: go mod download && go mod tidy

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az --version


  test-store-types:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: list dir
        run: ls -la

      - name: Get secret from Azure Key Vault
        run: |
          . ./examples/auth/akv/akv_auth.sh
#          export VAULT_NAME="kfutil"
#          export SECRET_NAME="integration-labs"
#
#          export METADATA_URL="http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https://vault.azure.net"
#          echo "Metadata URL: $METADATA_URL"
#
#          # Make a request to the metadata endpoint
#          echo "Querying metadata endpoint for access token..."
#          TOKEN_JSON=$(curl -H "Metadata: true" $METADATA_URL)
#
#          echo "Exporting access token to ACCESS_TOKEN variable..."
#          # Parse the access token from the response JSON
#          export ACCESS_TOKEN=$(echo $TOKEN_JSON | jq -r .access_token)
#
#          # Now you can use the $ACCESS_TOKEN to authenticate and access Azure Key Vault
#          echo "Access Token: $ACCESS_TOKEN"
#
#          export SECRET_URL="https://${VAULT_NAME}.vault.azure.net/secrets/${SECRET_NAME}?api-version=7.0"
#          echo "Secret URL: $SECRET_URL"
#
#
#          # Get the secret value from Azure Key Vault
#          echo "Querying Azure Key Vault for secret value..."
#          SECRET_VALUE=$(curl -H "Authorization: Bearer ${ACCESS_TOKEN}" "$SECRET_URL" | jq -r .value)
#
#          echo "Secret Value: $SECRET_VALUE"
#          mkdir -p ~/.keyfactor
#          echo $SECRET_VALUE | jq -r . > ~/.keyfactor/command_config.json

      - name: Run tests
        working-directory: cmd
        run: go test ./storeTypes_test.go
